# Generated by Django 5.2.4 on 2025-08-03 19:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('status', models.CharField(choices=[('business', 'Бизнес'), ('personal', 'Личное'), ('tax', 'Налог')], max_length=20, verbose_name='Статус')),
                ('type', models.CharField(choices=[('income', 'Поступление'), ('expense', 'Списание')], max_length=20, verbose_name='Тип')),
                ('category', models.CharField(choices=[('salary', 'Зарплата'), ('freelance', 'Фриланс'), ('investments', 'Инвестиции'), ('sales', 'Продажи'), ('infrastructure', 'Инфраструктура'), ('marketing', 'Маркетинг'), ('food', 'Еда'), ('transport', 'Транспорт'), ('entertainment', 'Развлечения')], max_length=20, verbose_name='Категория')),
                ('subcategory', models.CharField(choices=[('vps', 'VPS'), ('proxy', 'Proxy'), ('domains', 'Домены'), ('ssl', 'SSL-сертификаты'), ('farpost', 'Farpost'), ('avito', 'Avito'), ('yandex_direct', 'Яндекс.Директ'), ('google_ads', 'Google Ads'), ('products', 'Продукты'), ('restaurants', 'Рестораны'), ('delivery', 'Доставка'), ('fuel', 'Топливо'), ('public_transport', 'Общественный транспорт'), ('taxi', 'Такси'), ('cinema', 'Кино'), ('games', 'Игры'), ('books', 'Книги'), ('subscriptions', 'Подписки'), ('main_salary', 'Основная зарплата'), ('bonus', 'Премия'), ('web_dev', 'Веб-разработка'), ('design', 'Дизайн'), ('dividends', 'Дивиденды'), ('goods_sales', 'Продажа товаров')], max_length=20, verbose_name='Подкатегория')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Транзакция',
                'verbose_name_plural': 'Транзакции',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
